# Generated by Django 5.0.6 on 2024-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_chaivariety_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='chais/'),
        ),
    ]
