# Generated by Django 5.0.6 on 2024-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_alter_chaivariety_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
